version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install -g serverless
      - npm install

  build:
    commands:
      - echo "Building the project..."
      - serverless deploy

artifacts:
  files:
    - '**/*'
