ProductsIAM:
  Effect: Allow
  Action:
    - dynamodb:Query
    - dynamodb:GetItem
    - dynamodb:PutItem
    - dynamodb:UpdateItem
    - dynamodb:DeleteItem

  Resource:
    - arn:aws:dynamodb:${self:provider.region}:*:table/Products-${sls:stage}