Products:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: Products-${sls:stage}
    AttributeDefinitions:
      - AttributeName: ProductId
        AttributeType: S
    KeySchema:
      - AttributeName: ProductId
        KeyType: HASH
    BillingMode: PAY_PER_REQUEST
